DAO
edgaremirborbonjimenez/WEB-JAVA-PROYECT-JSP pull request #3
Opened 2023-11-14 18:48 UTC by arrcristian

2023-11-14 18:56 UTC, arrcristian commented
DAO

2023-11-15 00:09 UTC, edgaremirborbonjimenez requested changes
Agregale un atributo EntityManager y lo instancias en su sontructor que recibe un EntityManager, tambien agregar su funcionamiento en los metodos

2023-11-15 00:09 UTC, edgaremirborbonjimenez commented on src/Persistence/src/main/java/dao/implementation/Comentario.java
Agregale un atributo EntityManager y lo instancias en su sontructor que recibe un EntityManager, tambien agregar su funcionamiento en los metodos

2023-11-15 00:09 UTC, edgaremirborbonjimenez commented on src/Persistence/src/main/java/dao/implementation/Estado.java
Agregale un atributo EntityManager y lo instancias en su sontructor que recibe un EntityManager, tambien agregar su funcionamiento en los metodos

2023-11-15 00:09 UTC, edgaremirborbonjimenez commented on src/Persistence/src/main/java/dao/implementation/Municipio.java
Agregale un atributo EntityManager y lo instancias en su sontructor que recibe un EntityManager, tambien agregar su funcionamiento en los metodos

2023-11-15 00:09 UTC, edgaremirborbonjimenez commented on src/Persistence/src/main/java/dao/implementation/Post.java
Agregale un atributo EntityManager y lo instancias en su sontructor que recibe un EntityManager, tambien agregar su funcionamiento en los metodos

2023-11-15 00:09 UTC, edgaremirborbonjimenez commented on src/Persistence/src/main/java/dao/implementation/Usuario.java
Agregale un atributo EntityManager y lo instancias en su sontructor que recibe un EntityManager

2023-11-15 00:11 UTC, merged